#!/bin/sh

configure_sources_list() {
    if grep -q '^deb ' /etc/apt/sources.list; then
	echo "INFO: sources.list is configured, everything is fine"
	return
    fi

    echo "INFO: sources.list is empty, setting up a default one for Kali"

    cat >/etc/apt/sources.list <<END
# See https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
deb http://http.kali.org/kali kali-rolling main contrib non-free
# Additional line for source packages
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
END
    apt-get update
}

get_user_list() {
    for user in $(cd /home && ls); do
	if ! getent passwd "$user" >/dev/null; then
	    echo "WARNING: user '$user' is invalid but /home/$user exists"
	    continue
	fi
	echo "$user"
    done
    echo "root"
}

configure_zsh() {
    if grep -q 'nozsh' /proc/cmdline; then
	echo "INFO: user opted out of zsh by default"
	return
    fi
    if [ ! -x /usr/bin/zsh ]; then
	echo "INFO: /usr/bin/zsh is not available"
	return
    fi
    for user in $(get_user_list); do
	echo "INFO: changing default shell of user '$user' to zsh"
	chsh --shell /usr/bin/zsh $user
    done
}
configure_usergroups() {
    addgroup --system kaboxer || true
    addgroup --system wireshark || true

    kali_groups="adm,kaboxer,dialout,wireshark"

    for user in $(get_user_list); do
	echo "INFO: adding user '$user' to groups '$kali_groups'"
	usermod -a -G "$kali_groups" $user || true
    done
}

plaguesec_finish_install() {
    # Set Plank Theme
    sudo mv /usr/share/plaguesec-files/dock.theme /usr/share/plank/themes/Default/dock.theme
    # Wireless Compatibility
    sudo rm /etc/network/interfaces
    sudo mv /etc/network/interface /etc/network/interfaces
    cat >/etc/network/interfaces <<END
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).
source /etc/network/interfaces.d/*
# The loopback network interface
auto lo
iface lo inet loopback
# The primary network interface
auto wlan0
END
    # Update System
    apt-get update
    
    # Used when KDE Build Fails (Black screen with cursor after login) 
    #sudo pkcon update -y
}


configure_sources_list
configure_zsh
configure_usergroups
plaguesec_finish_install
