#!/bin/sh

configure_zsh() {
    # Stop if zsh is not present
    if [ ! -x /usr/bin/zsh ]; then
	return
    fi
    # Stop if user has opted out of zsh
    if echo "${LIVE_CONFIG_CMDLINE}" | grep -qs 'nozsh'; then
	return
    fi
    chsh --shell /usr/bin/zsh robot
    chsh --shell /usr/bin/zsh root
}

configure_usergroups() {
    addgroup --system kaboxer || true  # Ensures the group exists
    addgroup --system wireshark || true  # Ensures the group exists
    # adm - read access to log files
    # kaboxer - for kaboxer
    # dialout - for serial port access
    # wireshark - capture sessions without being root
    groups="adm,kaboxer,dialout,wireshark"

    usermod -a -G $groups robot
}

# Avoid configuring multiple times in case persistence is enabled
if [ -e /var/lib/live/config/kali-user-setup ]; then
    exit 0
fi

# Set "plaguesec" as password for the user robot
usermod -p '$2a$04$xQrz0w4ldhR1HZvO5Z4GN.ssBfTPdeN/EcvFb60Nl5ckIeF5ILFtC' robot

# Change default shell to zsh
configure_zsh

# Add kali user to additional groups
configure_usergroups

# Remember that this script has been run
touch /var/lib/live/config/kali-user-setup
